### ISSUE TITLE
Linter for docstrings

### ISSUE THREAD

**Issue by palt0** [Parnassius/cerbottana#110]
[Darglint](https://github.com/terrencepreilly/darglint) is a good option. We may consider removing type hints from docstrings to avoid generating `DAR103` false positives for optional arguments.

**Comment by palt0** [comment]
This has been ready for quite a while but I wanted to avoid opening a PR that changes a lot of source files during a major refactor.
Since these are trivial changes, though, I'd implement them rigth after #164 and before #167.

darglint doesn't support the `(type, optional)` syntax, but honestly we could just drop the `optional` keyword.
See my [darglint2](https://github.com/palt0/cerbottana/tree/darglint2) branch for an implementation.

**Comment by Parnassius** [comment]
If darglint doesn't support `optional` (and no similar tools exist) I have no objections to dropping it. I only have a question: why are you using `-not -path "./.*"` in the workflow file?
