### ISSUE TITLE
Per-room eightball answers

### ISSUE THREAD

**Issue by Parnassius** [Parnassius/cerbottana#167]
I already pushed the alemic script to [per-room-eightball-wip](https://github.com/Parnassius/cerbottana/tree/per-room-eightball-wip), I'm creating this issue just to jot down some notes. I'd probably wait for #164 to be merged before working on this.
- [ ] Default answers should either:
  - be excluded from the database, and hardcoded in the `.eightball` command, taking the room language into consideration
  - be inserted into the database when needed (probably when someone tries to use `.eightball` and the database has no records?)
- [ ] `.addeightballanswer` and `.removeeightballanswer` should use `parametrize_room` instead of `main_room_only`, and should log in the room modlog if the commands were made in pms
- [ ] `.removeeightballanswerid` should use `parametrize_room` as well, and always log to the room modlog
- [ ] the htmlpage should be available for room drivers, and maybe in read only mode for everyone else?

**Comment by palt0** [comment]
>  the htmlpage should be available for room drivers, _and maybe in read only mode for everyone else?_

I'd keep them secret because discovering them is more fun, but maybe it's just me! Differently from quotes, these phrases shouldn't really have a inherent meaning anyway.

**Comment by Parnassius** [comment]
che cazzo fai sveglio alle 6 di mattina
