### ISSUE TITLE
Command to display pokemon sprites

### ISSUE THREAD

**Issue by palt0** [Parnassius/cerbottana#182]
(Originally requested by Milak.)

I already wrote all of the code, but I wanted to know if you're fine with using [imageprobe](https://github.com/palt0/imageprobe) to fetch image dimensions.

**Comment by Parnassius** [comment]
> if you're fine with using [imageprobe](https://github.com/palt0/imageprobe)

no objections here

**Comment by palt0** [comment]
The only thing that should probably be discussed is the actual syntax of the command.
The simplest implementation would involve two separate commands to distinguish between regular and shiny forms. 
I guess it's probably better to use a single command and pass `shiny` as a parameter though, because it seems more natural to just write `.sprite shiny tapu lele` than `.shinysprite tapu lele` and it's also more extensible (for example I could add a parameter for pastgen sprites in the future).
We should also allow both `shiny tapu lele` and `tapu lele shiny` as valid inputs.

**Comment by Parnassius** [comment]
I would do a single command as well, but I'd use a comma to separate `shiny` from the pokemon name, so `.sprite tapu lele, shiny` (or `.sprite shiny, tapu lele`)

**Comment by palt0** [comment]
This is also fine and it's also more consistent with the rest of the commands.
