### ISSUE TITLE
Code re-organization

### ISSUE THREAD

**Issue by palt0** [Parnassius/cerbottana#186]
In case you agree, I created commits for all of these points (https://github.com/palt0/cerbottana/commits/code-reorganization).

### Source files should have source code (crazy, I know)

- [x] Move `utils.AVATAR_IDS` to `data/`.
- [x] Move the dict of letters for `.say` to `data/`. The main drawback for this would be losing readability (unless you don't want to store it in JSON), which isn't a big deal since we woudn't edit that data anyway.

### Other possible changes

- [x] ~Move `.dashboard` in `plugins.misc`. At this point it's just a legacy message, it doesn't warrant a module of its own. Or are you planning to expand this feature in the future?~ Remove `.dashboard`.

**Comment by Parnassius** [comment]
> * [ ]  Move `utils.AVATAR_IDS` to `data/`.

I completely agree

> * [ ]  Move the dict of letters for `.say` to `data/`. The main drawback for this would be losing readability (unless you don't want to store it in JSON), which isn't a big deal since we woudn't edit that data anyway.

Honestly I'd prefer keeping them readable, just in case. Ltner

> 
> 
> ### Other possible changes
> 
>     * [ ]  Move `.dashboard` in `plugins.misc`. At this point it's just a legacy message, it doesn't warrant a module of its own. Or are you planning to expand this feature in the future?

**Comment by palt0** [comment]
> Honestly I'd prefer keeping them readable, just in case. Otherwise i agree on this point as well.
I used UTF-8.

All done.
