### ISSUE TITLE
Support custom ranks

### ISSUE THREAD

**Issue by palt0** [Parnassius/cerbottana#76]
We received the request to support bot commands written by users with a custom rank. This is useful for a private room.
Parnassius told me to consider all non-alphanumeric characters that aren't already used for an official rank as valid custom ranks. 

I'm opening an issue because I created a mock implementation but I didn't get any feedback privately, and I'd rather discuss the implementation details before opening the PR.

Should I...
- Broaden the `voice` role of `utils.has_role` to include custom ranks. That's honestly the most straightforward and fitting approach in my opinion.
- Create a new role for `utils.has_role` that includes custom ranks alongside regular ones.
- Edit only `scope_checker` (`plugins/__init__.py`) without modifying or creating a role.

**Comment by Parnassius** [comment]
1

**Comment by palt0** [comment]
Then we'll have a 1:1 correlation between rank symbols (`+`, `%`, ...) and role strings (`voice`, `driver`, ...). Shall we just use symbols for the first parameter of the various `has_role` functions?
That would be coherent with the syntax used for `Room.send_rankhtmlbox()` and it would also simplify the underlying logic.

    utils.has_role("%", room)

I already mentioned this possibility to @Parnassius during the models refactor, but ironing out the details would have prolonged dev time.

_(In caso, preferirei fare questo PR come primissima cosa appena termini la LOA: è molto veloce ma freeza il development.)_
