### ISSUE TITLE
Proper setup for custom username colors data

### ISSUE THREAD

**Issue by palt0** [Parnassius/cerbottana#95]
The current implementation hardcodes custom username colors in a dictionary updated on a daily basis through a GH workflow. Furthermore, this dictionary is stored in a source file, so all the automatically generated commits are mixed with actual contributions.

Since the introduction of the workflow (https://github.com/Parnassius/cerbottana/commit/84ff01d0d621f7b80c2d2f39620a19251f915a90), these *"Update custom username colors"* commits have [slightly outnumbered the actual contributions committed by the code owner](https://github.com/Parnassius/cerbottana/commits?author=Parnassius&since=2020-09-30&until=2020-10-15), without considering commits that got reverted back. 

I'm opening this issue because I don't think this is a feasible setup in the long run and I'm sure this was supposed to be a temporary solution anyway. I'm not interested in working on it myself as of now, but I'll write down some insights and might add other comments in the future.

As a baseline, we should rely on the newly introduced `<username>` tag whenever it's possible. If we'll still need to store custom username colors, we should retrieve data dynamically after startup: cerbottana is restarted often and not having an updated username color isn't much impactful anyway.

**Comment by Parnassius** [comment]
/htmlbox <username name="parnassius"><div style="height: 40px; box-shadow: inset 0 0 0 100vh, 0 40px"></div></username><span>Parnassius</span><username name="parnassius"><div style="height: 40px; box-shadow: inset 0 0 0 100vh, 0 -40px"></div></username>

**Comment by Parnassius** [comment]
e99f35802985e75637064308253d4ce835bb141b i forgot again ok?
